# architecture settings
dim_emb: 128
dim_en_latent: 128
num_en_resblock: 4
num_en_channels: 128
conv_kernel_size: 3
resblock_pre_activation: True


# residual strided convs if False then maxpooling 
residual_strided_convs: True
strided_conv_num: None # decided by a helper function if not assigned a number (see run_exp.py)


# dilation settings
dilation_type: exponential

# if linear dilation
dilation_base: 1
dilation_slope: 1

# if constant dilation
dilation_constant: 1

# activation function settings
activation_linear: "lecuntanh"
activation_conv: prelu

#if prelu 
prelu_params: 1

#if leakyrelu
relu_slope: 0.2

# embedding normalization
encoder_normalize_embedding: False

# weight normalization
weightnorm_type: "weightnorm" # "weightnorm" or "none"
weightnorm_dim: 0

# normalization
layernorm_type: "layernorm"
layernorm_elementwise_affine: True



# if adanorm 
adanorm_k: 0.1
adanorm_scale: 1.0
eps: 1e-8



# optimizer settings
optimizer: "sgd"
momentum: 0.8
weight_decay_mode: "linear"
weight_decay: 0.001
wd_max: 0.001
wd_min: 0.0001
lr_init: 1e-5

# scheduler settings
min_lr: 1e-7
sched_pat: 40
sched_cooldown: 20
lr_reduce_factor: 0.5
mode: "min"
threshold_mode: "abs"
threshold: 1e-03