# architecture settings 
hidden_dim: 256
weight_model_layers: 2
weight_model_channels: 128
token_dim: 8
num_tokens: 16
kernel_size: 3
use_pos_enc: False

# optimizer settings
optimizer: "adam"
lr_init: 1e-5

# scheduler settings
min_lr: 1e-7
mode: "min"
lr_reduce_factor: 0.5
lr_scheduler_patience: 40
sched_cooldown: 20
threshold_mode: "abs"
threshold: 1e-03